// app
export const SIDEBAR_COLLAPSED_TOGGLE = 'SIDEBAR_COLLAPSED_TOGGLE'
export type SIDEBAR_COLLAPSED_TOGGLE_TYPE = typeof SIDEBAR_COLLAPSED_TOGGLE
export const SHOW_RIGHT_PANEL_TOGGLE = 'SHOW_RIGHT_PANEL'
export type SHOW_RIGHT_PANEL_TOGGLE_TYPE = typeof SHOW_RIGHT_PANEL_TOGGLE

// settings
export const SHOW_LOGO_TOGGLE = 'SHOW_LOGO_TOGGLE'
export type SHOW_LOGO_TOGGLE_TYPE = typeof SHOW_LOGO_TOGGLE
export const FIX_HEADER_TOGGLE = 'FIX_HEADER_TOGGLE'
export type FIX_HEADER_TOGGLE_TYPE = typeof FIX_HEADER_TOGGLE
export const OPEN_TAGS_VIEW = 'OPEN_TAGS_VIEW'
export type OPEN_TAGS_VIEW_TYPE = typeof OPEN_TAGS_VIEW

// user
export const SET_TOKEN = 'SET_TOKEN'
export type SET_TOKEN_TYPE = typeof SET_TOKEN
export const RESET_USER = 'RESET_USER'
export type RESET_USER_TYPE = typeof RESET_USER
export const GET_USERINFO = 'GET_USERINFO'
export type GET_USERINFO_TYPE = typeof GET_USERINFO
export const SET_USERINFO = 'SET_USERINFO'
export type SET_USERINFO_TYPE = typeof SET_USERINFO

// auth
export const AUTH_LOGIN = 'AUTH_LOGIN'
export type AUTH_LOGIN_TYPE = typeof AUTH_LOGIN
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export type AUTH_LOGOUT_TYPE = typeof AUTH_LOGOUT

// tagsView
export const ADD_TAGS_VIEW = 'TAGS_VIEW'
export type ADD_TAGS_VIEW_TYPE = typeof ADD_TAGS_VIEW
export const REMOVE_TAGS_VIEW = 'REMOVE_TAGS_VIEW'
export type REMOVE_TAGS_VIEW_TYPE = typeof REMOVE_TAGS_VIEW
export const CLOSE_ALL_TAGS_VIEW = 'CLOSE_ALL_TAGS_VIEW'
export type CLOSE_ALL_TAGS_VIEW_TYPE = typeof CLOSE_ALL_TAGS_VIEW
export const CLOSE_OTHERS_TAG_VIEW = 'CLOSE_OTHERS_TAG_VIEW'
export type CLOSE_OTHERS_TAG_VIEW_TYPE = typeof CLOSE_OTHERS_TAG_VIEW
